### ISSUE TITLE
RM toolkit

### ISSUE THREAD

**Issue by martonmiklos** [martonmiklos/robomow_city120_reveng#1]
Hi @lve0200

If you were active here:
https://www.roboter-forum.com/core/index.php?user/34701-lve0200/

Could you please check you private messages? I am looking for the mentioned toolkit but cannot find anywhere.

**Comment by mattncsu** [comment]
see https://transfernow.net/54kq74m6qd5a

**Comment by martonmiklos** [comment]
Hi @mattncsu !

Thanks for the files, actually I have this already (these stuff was available on the robomow's FTP for a while).

Unfortunately this toolkit is for the newer generations (RX/RC/RS) which uses different protocol. 

There used to be a tool called "RM toolkit" (not Robomow toolkit) mentioned here:
http://www.fedal.it/doc/prova1.pdf

![kép](https://user-images.githubusercontent.com/1609182/60753966-8be15c80-9fda-11e9-86ad-86f7283ad861.png) 

This is what I am looking for. Yes I know it is for the RM series not the RL (what I have), but it was closer in time to that, and they used the same RJ11 connector approach.
